# [formatter.nix]
# command = "alejandra"
# includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
# options = ["--plugin", "prettier-plugin-toml", "--write"]
includes = ["*.md", "*.yaml", "*.toml"]
excludes = ["CHANGELOG.md", "encrypted/*", "*.enc.json", "*.enc.yaml"]

[formatter.shell]
command = "sh"
options = [
    "-eucx",
    """
# This is a bug in treefmt, the script should not be called without arguments
if [[ $# -le 0 ]]; then exit 0; fi
# First shellcheck
shellcheck --external-sources --source-path=SCRIPTDIR "$@"
# Then format
shfmt -i 2 -s -w "$@"
    """
]
includes = ["*.sh"]
excludes = []

[formatter.terraform]
# Terraform fmt only takes one file at the time so we create a wrapper.
# See https://github.com/numtide/treefmt/issues/97
command = "/bin/sh"
options = [
    "-euc",
    """
for f in "$@"; do
  terraform fmt "$f"
done
    """,
    "--",
]
includes = ["*.tf"]
